apiVersion: apps/v1
kind: Deployment
metadata:
  #name: db-deployment
  name: {{ .Release.Name }}-deployment
  labels:
    app: db
spec:
  #replicas: 1
  replicaCount: {{ .Values.replicaCount }} 
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data-pvc
      containers:
        - name: db-container
          #image: postgres:14.1
          image: {{ .Values.image }}.{{ .Values.image.tag }}
          ports:
            - containerPort: 5432
                volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data 
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: db_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: db_password             
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-configmap
                  key: db_host
